In [1]:
import sqlite3
import pandas as pd

In [2]:
conn=sqlite3.connect("northwind.db")
print("Database connected successfully!")

Database connected successfully!

In [3]:
query="""
SELECT name
FROM sqlite_master
WHERE type='table';
"""
tables=pd.read_sql(query,conn)

tables

                    name
0             Categories
1        sqlite_sequence
2   CustomerCustomerDemo
3   CustomerDemographics
4              Customers
5              Employees
6    EmployeeTerritories
7          Order Details
8                 Orders
9               Products
10               Regions
11              Shippers
12             Suppliers
13           Territories

In [4]:
query=""" 
SELECT 
ProductName,
UnitPrice
FROM Products
LIMIT 5;
"""
pd.read_sql(query,conn)

                    ProductName  UnitPrice
0                          Chai      18.00
1                         Chang      19.00
2                 Aniseed Syrup      10.00
3  Chef Anton's Cajun Seasoning      22.00
4        Chef Anton's Gumbo Mix      21.35

# Northwind Database Analysis
## SQL Analysis & Business Insights

In [5]:
query =""" 
SELECT 
p.ProductName,
SUM(od.Quantity) AS TotalSold
FROM Products p
JOIN "Order Details" od ON p.ProductID = od.ProductID
GROUP BY p.ProductName
ORDER BY TotalSold DESC
LIMIT 10;
"""

top_products=pd.read_sql(query,conn)
top_products

                       ProductName  TotalSold
0        Louisiana Hot Spiced Okra     206213
1           Sir Rodney's Marmalade     205637
2       Teatime Chocolate Biscuits     205487
3                   Sirop d'érable     205005
4              Gumbär Gummibärchen     204761
5                    Outback Lager     204403
6                   Ravioli Angelo     204251
7             Raclette Courdavault     204137
8  Uncle Bob's Organic Dried Pears     203970
9                    Sasquatch Ale     203667

In [6]:
query =""" 
SELECT 
c.CompanyName,
ROUND(SUM(od.UnitPrice * od.Quantity), 2)AS Revenue
FROM Customers c
JOIN Orders o ON c.CustomerID = o.CustomerID
JOIN "Order Details" od ON o.OrderID = od.OrderID
GROUP BY c.CompanyName
ORDER BY Revenue DESC 
LIMIT 10;
"""
top_customers=pd.read_sql(query,conn)
top_customers

                          CompanyName     Revenue
0                                  IT  9745371.29
1                       B's Beverages  6154115.34
2          Hungry Coyote Import Store  5698023.67
3                       Rancho grande  5559110.08
4                 Gourmet Lanchonetes  5552597.90
5  Ana Trujillo Emparedados y helados  5534356.65
6                  Ricardo Adocicados  5524990.91
7                   Folies gourmandes  5505502.85
8                   Let's Stop N Shop  5462611.57
9                   LILA-Supermercado  5439186.80

In [7]:
pd.read_sql("PRAGMA table_info(Orders);", conn)

    cid            name      type  notnull dflt_value  pk
0     0         OrderID   INTEGER        1       None   1
1     1      CustomerID      TEXT        0       None   0
2     2      EmployeeID   INTEGER        0       None   0
3     3       OrderDate  DATETIME        0       None   0
4     4    RequiredDate  DATETIME        0       None   0
5     5     ShippedDate  DATETIME        0       None   0
6     6         ShipVia   INTEGER        0       None   0
7     7         Freight   NUMERIC        0          0   0
8     8        ShipName      TEXT        0       None   0
9     9     ShipAddress      TEXT        0       None   0
10   10        ShipCity      TEXT        0       None   0
11   11      ShipRegion      TEXT        0       None   0
12   12  ShipPostalCode      TEXT        0       None   0
13   13     ShipCountry      TEXT        0       None   0

In [8]:
query =""" 
SELECT 
strftime('%Y-%m', o.OrderDate) AS Month,
ROUND(SUM(od.UnitPrice * od.Quantity), 2) AS Sales
FROM Orders o
JOIN "Order Details" od ON o.OrderID = od.OrderID
GROUP BY Month
ORDER BY Month;
"""
monthly_sales=pd.read_sql(query,conn)
monthly_sales

       Month       Sales
0    2012-07  2066219.40
1    2012-08  3556875.79
2    2012-09  3440144.98
3    2012-10  3201529.96
4    2012-11  2980494.74
..       ...         ...
131  2023-06  3071787.73
132  2023-07  3350337.36
133  2023-08  3293158.67
134  2023-09  3544698.51
135  2023-10  2923364.35

[136 rows x 2 columns]

In [9]:
query =""" 
SELECT 
c.CategoryName, 
ROUND(SUM(od.UnitPrice * od.Quantity) , 2) Revenue
FROM Categories c
JOIN Products p ON c.CategoryID = p.CategoryID
JOIN "Order Details" od ON p.ProductID = od.ProductID
Group BY c.CategoryName
ORDER BY Revenue DESC;
"""
categories = pd.read_sql(query,conn)
categories

     CategoryName      Revenue
0       Beverages  92181842.95
1     Confections  66347544.94
2    Meat/Poultry  64896314.41
3  Dairy Products  58034940.00
4      Condiments  55802774.45
5         Seafood  49931965.52
6         Produce  32706403.90
7  Grains/Cereals  28573512.55

In [10]:
query = """ 
SELECT
c.CompanyName,COUNT(o.OrderID) AS OrdersPlaced
FROM Customers c
JOIN Orders o
ON c.CustomerId = o.CustomerId
GROUP BY c.CompanyName
ORDER BY OrdersPlaced DESC;
"""
purchase_frequency = pd.read_sql(query,conn)
purchase_frequency
purchase_frequency.head(10)

                          CompanyName  OrdersPlaced
0                                  IT           335
1                       B's Beverages           210
2                  Ricardo Adocicados           203
3                   LILA-Supermercado           203
4                 Gourmet Lanchonetes           202
5              Princesa Isabel Vinhos           200
6          Hungry Coyote Import Store           198
7                 Tortuga Restaurante           197
8                   Folies gourmandes           195
9  Ana Trujillo Emparedados y helados           195

In [11]:
top_products.describe()

           TotalSold
count      10.000000
mean   204753.100000
std       820.692452
min    203667.000000
25%    204165.500000
50%    204582.000000
75%    205366.500000
max    206213.000000

In [12]:
top_customers.describe()

            Revenue
count  1.000000e+01
mean   6.017587e+06
std    1.326000e+06
min    5.439187e+06
25%    5.510375e+06
50%    5.543477e+06
75%    5.663295e+06
max    9.745371e+06

In [13]:
monthly_sales.describe()

              Sales
count  1.360000e+02
mean   3.297612e+06
std    3.885407e+05
min    2.066219e+06
25%    3.050957e+06
50%    3.286028e+06
75%    3.518739e+06
max    4.377795e+06

## Business Insights

1. A small number of products contribute significantly to the overall sales volume.

2. A limited group of customers generates the highest revenue for the business.

3. Monthly sales fluctuate, indicating variations in customer demand over time.

4. Certain product categories consistently outperform others in terms of revenue.

5. Customers with higher purchase frequency contribute significantly to overall sales and are valuable for long-term business growth.